# Generated by Django 4.2.1 on 2023-05-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_booking_member_menu_service_social_subscriber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='subject',
        ),
        migrations.AddField(
            model_name='booking',
            name='select',
            field=models.CharField(choices=[('select1', 'select1'), ('select2', 'select2'), ('select3', 'select3')], default='max_lenght=100', max_length=7),
            preserve_default=False,
        ),
    ]
