# Generated by Django 4.2.1 on 2023-05-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_booking_subject_booking_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
