# Generated by Django 4.2.1 on 2023-05-05 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_booking_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
